version: 2.0
jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install_dependencies:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
        - restore_cache:
            keys:
              - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - run: yarn install

  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build

  lint:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build

workflows:
  version: 2
  lint_and_build:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
