# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  install:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install

  build:
    docker:
      -image: circleci/node:7.10
      working_directory: ~/repo
      steps:
        - checkout
        - run: yarn build

  lint:
    docker:
      -image: circleci/node:7.10
      working_directory: ~/repo
      steps:
        -checkout
        - run: yarn lint


workflows:
  version: 2
  checkout_lint_build:
    jobs:
      - install
      - lint:
        requires:
          - install
      - build:
        requires:
          - install
